apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-web
  ports:
  - protocol: TCP
    {{- if and 
    (eq .Values.web.service.type "NodePort") 
    (.Values.web.service.nodePort) 
    }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
    port: 80 
    targetPort: 8080 
  type: {{ .Values.web.service.type }}