# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-temperatura
  template:
    metadata:
      labels:
        app: web-temperatura
    spec:
      containers:
        - name: container-app
          image: felippedeiro/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: web-temperatura
  ports:
    - port: 80
      # vai bater na porta 80 do service, mas vai ser redirecionado pra porta 8080 do container
      targetPort: 8080
      nodePort: 30000
  type: NodePort