# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: felippedeiro/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: web-temperatura
spec:
  selector:
    app: web
  ports:
    - port: 80
      # vai bater na porta 80 do service, mas vai ser redirecionado pra porta 5000 do container
      targetPort: 8080
      nodePort: 30000
  type: NodePort